//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainiacApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainiacApp.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this test, you need to keep your eyes closed.
        ///You will hear some instructions and take actions
        ///accordingly. These instructions will be related to
        ///thinking or imagining objects/scenarios..
        /// </summary>
        internal static string T1Info1 {
            get {
                return ResourceManager.GetString("T1Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be given 6 instructions in total and for each
        ///instruction you will be given some time. During test try
        ///not to think anything else..
        /// </summary>
        internal static string T1Info2 {
            get {
                return ResourceManager.GetString("T1Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between instructions you will be given 5 seconds
        ///resting time. During that time keep your eyes closed
        ///and try not to think anything..
        /// </summary>
        internal static string T1Info3 {
            get {
                return ResourceManager.GetString("T1Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think of the object “bike”. .
        /// </summary>
        internal static string T1Q1 {
            get {
                return ResourceManager.GetString("T1Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize the object “car” in yor mind..
        /// </summary>
        internal static string T1Q2 {
            get {
                return ResourceManager.GetString("T1Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize a bumblebee with a head of bull in your head..
        /// </summary>
        internal static string T1Q3 {
            get {
                return ResourceManager.GetString("T1Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize an imaginary place you would love to be in.
        ///This place should not exist in real world..
        /// </summary>
        internal static string T1Q4 {
            get {
                return ResourceManager.GetString("T1Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize an imaginary event in your mind. This
        ///event should not have happened in real life. It can
        ///be totally fiction or inspired from real life events..
        /// </summary>
        internal static string T1Q5 {
            get {
                return ResourceManager.GetString("T1Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be shown 3 pictures one by one. For each
        ///picture you will be given 20 seconds. During those 
        ///whole 20 seconds, you should think about what the
        ///picture reminds you of..
        /// </summary>
        internal static string T2Info1 {
            get {
                return ResourceManager.GetString("T2Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pictures might remind you of things related to 
        ///real life or fiction. Try hard to make connections..
        /// </summary>
        internal static string T2Info2 {
            get {
                return ResourceManager.GetString("T2Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between pictures you will have 10 seconds rest. 
        ///Free your mind..
        /// </summary>
        internal static string T2Info3 {
            get {
                return ResourceManager.GetString("T2Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does this picture resemble to you?
        ///(Can be multiple things).
        /// </summary>
        internal static string T2Q {
            get {
                return ResourceManager.GetString("T2Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be a 3x3 board consisting of squares. Each question will consist of 3 parts. .
        /// </summary>
        internal static string T3Info1 {
            get {
                return ResourceManager.GetString("T3Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the first part, a square will light up and a letter will be shown on it..
        /// </summary>
        internal static string T3Info2 {
            get {
                return ResourceManager.GetString("T3Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to remember the square and the letter. In the third part you will have choices to select. .
        /// </summary>
        internal static string T3Info3 {
            get {
                return ResourceManager.GetString("T3Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the square and the letter matches the ones from the first part, then you select both match..
        /// </summary>
        internal static string T3Info4 {
            get {
                return ResourceManager.GetString("T3Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If they do not match, you select no match. If only one of them matches you select the corresponding match..
        /// </summary>
        internal static string T3Info5 {
            get {
                return ResourceManager.GetString("T3Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think of a verb related to given noun..
        /// </summary>
        internal static string T4Info {
            get {
                return ResourceManager.GetString("T4Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencil.
        /// </summary>
        internal static string T4Q1 {
            get {
                return ResourceManager.GetString("T4Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string T4Q2 {
            get {
                return ResourceManager.GetString("T4Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string T4Q3 {
            get {
                return ResourceManager.GetString("T4Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string T4Q4 {
            get {
                return ResourceManager.GetString("T4Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string T4Q5 {
            get {
                return ResourceManager.GetString("T4Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be given some commands randomly. This commands will say either.
        /// </summary>
        internal static string T5Info1 {
            get {
                return ResourceManager.GetString("T5Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Go” or “Don’t Go”. If you see “Go” you should click the button which says “Go”..
        /// </summary>
        internal static string T5Info2 {
            get {
                return ResourceManager.GetString("T5Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you see “Don’t Go”, you should wait till the next command arrives..
        /// </summary>
        internal static string T5Info3 {
            get {
                return ResourceManager.GetString("T5Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T5Q1 {
            get {
                return ResourceManager.GetString("T5Q1", resourceCulture);
            }
        }
    }
}
