//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainiacApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainiacApp.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hello benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During this test, you need to keep your eyes closed.
        ///You will hear some instructions and take actions
        ///accordingly. These instructions will be related to
        ///thinking or imagining objects/scenarios. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Info1 {
            get {
                return ResourceManager.GetString("T1Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be given 6 instructions in total and for each
        ///instruction you will be given some time. During test try
        ///not to think anything else. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Info2 {
            get {
                return ResourceManager.GetString("T1Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Between instructions you will be given 5 seconds
        ///resting time. During that time keep your eyes closed
        ///and try not to think anything. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Info3 {
            get {
                return ResourceManager.GetString("T1Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question1 of Test1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Q1 {
            get {
                return ResourceManager.GetString("T1Q1", resourceCulture);
            }
        }
    }
}
