//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainiacApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainiacApp.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hello benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During this test, you need to keep your eyes closed.
        ///You will hear some instructions and take actions
        ///accordingly. These instructions will be related to
        ///thinking or imagining objects/scenarios. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Info1 {
            get {
                return ResourceManager.GetString("T1Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be given 6 instructions in total and for each
        ///instruction you will be given some time. During test try
        ///not to think anything else. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Info2 {
            get {
                return ResourceManager.GetString("T1Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Between instructions you will be given 5 seconds
        ///resting time. During that time keep your eyes closed
        ///and try not to think anything. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Info3 {
            get {
                return ResourceManager.GetString("T1Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Think of the object “bike”.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Q1 {
            get {
                return ResourceManager.GetString("T1Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visualize the object “car” in yor mind. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Q2 {
            get {
                return ResourceManager.GetString("T1Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visualize a bumblebee with a head of bull in your head. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Q3 {
            get {
                return ResourceManager.GetString("T1Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visualize an imaginary place you would love to be in.
        ///This place should not exist in real world. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Q4 {
            get {
                return ResourceManager.GetString("T1Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visualize an imaginary event in your mind. This
        ///event should not have happened in real life. It can
        ///be totally fiction or inspired from real life events. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T1Q5 {
            get {
                return ResourceManager.GetString("T1Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be shown 3 pictures one by one. For each
        ///picture you will be given 20 seconds. During those 
        ///whole 20 seconds, you should think about what the
        ///picture reminds you of. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T2Info1 {
            get {
                return ResourceManager.GetString("T2Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pictures might remind you of things related to 
        ///real life or fiction. Try hard to make connections. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T2Info2 {
            get {
                return ResourceManager.GetString("T2Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Between pictures you will have 10 seconds rest. 
        ///Free your mind. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T2Info3 {
            get {
                return ResourceManager.GetString("T2Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What does this picture resemble to you?
        ///(Can be multiple things) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T2Q {
            get {
                return ResourceManager.GetString("T2Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There will be a 3x3 board consisting of squares. Each question will 
        ///consist of 3 parts. In the first part, a square will light up and a letter
        ///will be shown on it. You have to remember the square and the letter.
        ///This will be repeated for the second part and the third part too. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T3Info1 {
            get {
                return ResourceManager.GetString("T3Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In the third part you will have choices to select. If the square and the
        ///letter matches the ones from the first part, then you select both match.
        ///If they do not match, you select no match. If only one of them matches
        ///you select the corresponding match. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T3Info2 {
            get {
                return ResourceManager.GetString("T3Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For first and second parts you will have 3 seconds. For the third part,
        ///You will have 4 seconds. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T3Info3 {
            get {
                return ResourceManager.GetString("T3Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will be repeated for 7 times. There will not be rest times. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T3Info4 {
            get {
                return ResourceManager.GetString("T3Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be given a noun and then you should think of a verb
        ///related to it. Then you need to enter the verb into a text box. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Info1 {
            get {
                return ResourceManager.GetString("T4Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   However, try to think of unusal verbs. Do not write the most
        ///common verb you can think of. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Info2 {
            get {
                return ResourceManager.GetString("T4Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be given 15 seconds for each noun. Do not leave
        ///the textbox empty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Info3 {
            get {
                return ResourceManager.GetString("T4Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be given 5 second rest time between each noun. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Info4 {
            get {
                return ResourceManager.GetString("T4Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pencil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Q1 {
            get {
                return ResourceManager.GetString("T4Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Q2 {
            get {
                return ResourceManager.GetString("T4Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Q3 {
            get {
                return ResourceManager.GetString("T4Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Family benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Q4 {
            get {
                return ResourceManager.GetString("T4Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   School benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T4Q5 {
            get {
                return ResourceManager.GetString("T4Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be given some commands randomly. This commands
        ///will say either “Go” or “Don’t Go”. If you see “Go” you should
        ///click the button which says “Go”. If you see “Don’t Go”, you
        ///should wait till the next command arrives. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T5Info1 {
            get {
                return ResourceManager.GetString("T5Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your speed will be important because commands will
        ///stay 2-5 seconds. If you fail commands, it
        ///will be noted. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T5Info2 {
            get {
                return ResourceManager.GetString("T5Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This test will last in total 40 seconds. There will be no rest. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T5Info3 {
            get {
                return ResourceManager.GetString("T5Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string T5Q1 {
            get {
                return ResourceManager.GetString("T5Q1", resourceCulture);
            }
        }
    }
}
